apiVersion: v1
kind: Pod
metadata:
    name: my-pod
    labels:
        app: nginx
spec:
    containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---------------------------------------------------------------------------------

# REPLICATION CONTROLLER

apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: rs
spec:
    selector:
       matchExpressions:
           - {key: type, operator: In, values: ["frontend"]}
    replicas: 5
    template:
       metadata:
           name: my-pod
           labels: 
               type: frontend
            spec:
             containers:
                   - name: nginx
                     image: nginx:latest
                     ports:
                       - containerPort: 80
---------------------------------------------------------------------------------

